Repository minvws/nl-kat-coordination, pull requests merged in 2023-04, with the labels that each got.

#597 Change mula Debian package to always use PostgreSQL
  .github/workflows/test_debian_packages_on_ubuntu.yml
  docs/source/technical_design/debianinstall.rst
  mula/debian/install
  mula/debian/rules
  mula/packaging/deb/data/etc/kat/mula.conf
  mula/packaging/deb/data/usr/bin/update-mula-db
  mula/scheduler/context/context.py
Labels: sprint-5, backport1.7

#667 Log pdflatex output on error
  keiko/keiko/keiko.py
Labels: keiko, backport1.7

#671 Keiko output context data
  keiko/keiko/api.py
  keiko/keiko/keiko.py
  keiko/keiko/settings.py
Labels: keiko

#681 Update to xtdb-http-multinode v1.0.4
  .github/workflows/test_debian_packages_on_ubuntu.yml
  docker-compose.release-example.yml
Labels: sprint-6

#128 Translate Dutch images in docs to English
  README.rst
  docs/source/introduction/img/flowopenkat.png
  docs/source/introduction/img/modulesopenkat.png
  docs/source/introduction/img/stappenopenkat.png
Labels: sprint-6

#647 Handle errors from Octopoes connector
  octopoes/octopoes/connector/__init__.py
  octopoes/octopoes/connector/octopoes.py
  rocky/crisis_room/views.py
  rocky/rocky/views/finding_list.py
Labels: rocky, sprint-6

#705 Move indemnification warnings to templates
  rocky/rocky/templates/organizations/organization_crisis_room.html
  rocky/rocky/templates/organizations/organization_settings.html
  rocky/rocky/views/organization_crisis_room.py
  rocky/rocky/views/organization_settings.py
Labels: frontend, rocky

#700 Add reset() to expiring dict
  mula/scheduler/connectors/services/katalogus.py
  mula/scheduler/utils/dict_utils.py
Labels: mula

#637 Add debugging and troubleshooting page to the documentation
  docs/source/technical_design/debuggingtroubleshooting.rst
  docs/source/technical_design/img/dockerps.png
  docs/source/technical_design/img/healthpage.png
  docs/source/technical_design/index.rst
Labels: documentation, rocky

#713 Only have hostnames without a dot
  boefjes/README.md
  boefjes/boefjes/plugins/kat_crt_sh/main.py
  boefjes/boefjes/plugins/kat_crt_sh/normalize.py
  boefjes/boefjes/plugins/kat_dns/normalize.py
  boefjes/boefjes/plugins/kat_dns_zone/normalize.py
  boefjes/boefjes/plugins/kat_fierce/normalize.py
  boefjes/boefjes/plugins/kat_log4shell/description.md
  boefjes/tests/examples/dns-job.json
  boefjes/tests/examples/dns-normalize2.json
  boefjes/tests/examples/dummy.json
  boefjes/tests/examples/ipv6_nameservers.json
  boefjes/tests/examples/ipv6_nameservers_normalize.json
  boefjes/tests/examples/ipv6_webservers.json
  boefjes/tests/examples/ipv6_webservers_normalize.json
  boefjes/tests/examples/log4shell-job.json
  boefjes/tests/examples/scheduler/pop_response_boefje.json
  boefjes/tests/examples/scheduler/pop_response_normalizer.json
  boefjes/tests/examples/website_similarity.json
  boefjes/tests/examples/website_similarity_normalize.json
  boefjes/tests/test_dns.py
  boefjes/tests/test_manual.py
  bytes/tests/loading.py
  octopoes/bits/dns_alias_resolving/dns_alias_resolving.py
  octopoes/bits/dns_resolving/dns_resolving.py
  octopoes/bits/missing_dkim/missing_dkim.py
  octopoes/bits/missing_dmarc/missing_dmarc.py
  octopoes/bits/missing_spf/missing_spf.py
  octopoes/octopoes/models/ooi/dns/zone.py
  octopoes/tests/conftest.py
  octopoes/tests/fixtures/calvin_output_1.json
  octopoes/tests/fixtures/calvin_output_2.json
  octopoes/tests/fixtures/normalizer_output.json
  octopoes/tests/fixtures/normalizer_output_nxdomain.json
  octopoes/tests/fixtures/regular_manual_declaration.json
  octopoes/tests/fixtures/regular_manual_declaration_with_null_values.json
  octopoes/tests/test_api.py
  octopoes/tests/test_bit_spf_discovery.py
  octopoes/tests/test_ooi_repository.py
  octopoes/tests/test_reference_node.py
  rocky/onboarding/views.py
  rocky/tests/conftest.py
  rocky/tests/objects/test_objects.py
  rocky/tests/objects/test_objects_detail.py
  rocky/tests/objects/test_objects_scan_profile.py
  rocky/tests/test_boefjes_tasks.py
Labels: sprint-6

#718 Fix indemnification warning
  rocky/account/mixins.py
  rocky/rocky/templates/organizations/organization_crisis_room.html
  rocky/rocky/templates/organizations/organization_settings.html
Labels: rocky

#517 Update templates and add QA flow docs page
  .github/pull_request_template.md
  docs/source/conf.py
  docs/source/guidelines/feature_flow.md
  docs/source/guidelines/index.rst
  docs/source/templates/pull_request_template.md
Labels: documentation

#568 added indexes for findings
  rocky/rocky/templates/findings/finding_list.html
  rocky/rocky/views/finding_list.py
Labels: frontend, rocky, openkat-1.8

#542 chore/refactor katalogus settings setup
  boefjes/boefjes/katalogus/routers/settings.py
  rocky/Readme.md
  rocky/katalogus/client.py
  rocky/katalogus/templates/plugin_settings_delete.html
  rocky/katalogus/templates/plugin_settings_list.html
  rocky/katalogus/urls.py
  rocky/katalogus/views/change_clearance_level.py
  rocky/katalogus/views/katalogus.py
  rocky/katalogus/views/katalogus_settings.py
  rocky/katalogus/views/mixins.py
  rocky/katalogus/views/plugin_detail.py
  rocky/katalogus/views/plugin_detail_scan_oois.py
  rocky/katalogus/views/plugin_enable_disable.py
  rocky/katalogus/views/plugin_settings_add.py
  rocky/katalogus/views/plugin_settings_delete.py
  rocky/katalogus/views/plugin_settings_edit.py
  rocky/katalogus/views/plugin_settings_list.py
  rocky/onboarding/views.py
  rocky/rocky/views/mixins.py
  rocky/rocky/views/ooi_detail.py
  rocky/tests/conftest.py
  rocky/tests/katalogus/test_katalogus.py
  rocky/tests/katalogus/test_katalogus_plugin_add.py
  rocky/tests/katalogus/test_katalogus_plugin_delete.py
  rocky/tests/katalogus/test_katalogus_plugin_detail.py
  rocky/tests/katalogus/test_katalogus_plugin_edit.py
  rocky/tests/objects/test_objects_detail.py
  rocky/tests/test_organization.py
  rocky/tests/test_scans.py
Labels: sprint-6

#721 Do not propagate scan level from DNSSPFMechanismHostname
  octopoes/octopoes/models/ooi/email_security.py
Labels: sprint-6

#729 Cleanup Rocky requirements
  .pre-commit-config.yaml
  octopoes/tests/robot/02_list_objects.robot
  octopoes/tests/robot/05_bits.robot
  octopoes/tests/robot/robot.resource
  rocky/Dockerfile
  rocky/requirements-check.txt
  rocky/requirements-dev.txt
Labels: rocky, chore

#751 Add __repr__ to Task for scheduler
  mula/scheduler/models/tasks.py
  mula/scheduler/schedulers/boefje.py
  mula/scheduler/schedulers/normalizer.py
  mula/scheduler/schedulers/scheduler.py
Labels: mula

#767 Remove step to click 2FA button in the CI
  rocky/tests/robot/xxx.resource
Labels: bug, chore

#765 Move the ID of the button to the parent element
  rocky/katalogus/templates/katalogus.html
  rocky/katalogus/templates/partials/enable_disable_plugin.html
  rocky/katalogus/templates/partials/plugin_tile.html
Labels: UI/UX

#697 Retry on db disconnects in mula
  mula/scheduler/repositories/sqlalchemy/datastore.py
  mula/scheduler/repositories/sqlalchemy/pq_store.py
  mula/scheduler/repositories/sqlalchemy/task_store.py
Labels: mula

#740 Restructure mocks on tests
  mula/Makefile
  mula/README.md
  mula/tests/integration/test_boefje_scheduler.py
  mula/tests/integration/test_normalizer_scheduler.py
Labels: mula

#736 Add PR template code blocks for easier reviewing
  .github/pull_request_template.md
  docs/source/templates/index.rst
  docs/source/templates/pull_request_template.md
  docs/source/templates/pull_request_template_author.md
  docs/source/templates/pull_request_template_review_code.md
  docs/source/templates/pull_request_template_review_qa.md
Labels: chore

#730 Chore/bytes api consistency
  boefjes/boefjes/clients/bytes_client.py
  boefjes/boefjes/job_handler.py
  boefjes/tests/test_tasks.py
  bytes/.ci/.env.test
  bytes/bytes/api/__init__.py
  bytes/bytes/api/models.py
  bytes/bytes/api/router.py
  bytes/bytes/api/v2/__init__.py
  bytes/bytes/database/db_models.py
  bytes/bytes/database/migrations/versions/ec68d3eb14b1_remove_redundant_boefje_meta_foreign.py
  bytes/bytes/database/sql_meta_repository.py
  bytes/bytes/events/events.py
  bytes/bytes/models.py
  bytes/bytes/repositories/meta_repository.py
  bytes/sql_migrations/0016_ec68d3eb14b1_remove_redundant_boefje_meta_foreign.sql
  bytes/tests/client.py
  bytes/tests/conftest.py
  bytes/tests/integration/test_bytes_api.py
  bytes/tests/integration/test_hash_service.py
  bytes/tests/integration/test_meta_repository.py
  bytes/tests/integration/test_timestamper.py
  bytes/tests/loading.py
  bytes/tests/unit/test_context_mapping.py
  docs/source/introduction/makeyourown.rst
  rocky/rocky/bytes_client.py
  rocky/rocky/scheduler.py
  rocky/rocky/views/bytes_raw.py
Labels: bytes, tech-debt, chore

#809 Add OpenTelemetry tracing to Rocky and Octopoes
  .env-dist
  docker-compose.yml
  docs/source/technical_design/localinstall.rst
  octopoes/octopoes/api/api.py
  octopoes/octopoes/config/settings.py
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  rocky/requirements.txt
  rocky/rocky/middleware/otel.py
  rocky/rocky/otel.py
  rocky/rocky/settings.py
Labels: enhancement

#807 Clean up `setup.py` across all modules
  boefjes/setup.py
  bytes/setup.py
  keiko/setup.py
  mula/setup.py
  octopoes/setup.py
  rocky/setup.py
Labels: python

#758 Refactor views and update developer documentation
  docs/source/developer_documentation/index.rst
  docs/source/developer_documentation/rocky.md
  docs/source/index.rst
  rocky/Readme.md
  rocky/onboarding/views.py
  rocky/rocky/templates/oois/ooi_mute_finding.html
  rocky/rocky/views/finding_list.py
  rocky/rocky/views/finding_type_add.py
  rocky/rocky/views/health.py
  rocky/rocky/views/mixins.py
  rocky/rocky/views/ooi_delete.py
  rocky/rocky/views/ooi_detail.py
  rocky/rocky/views/ooi_detail_related_object.py
  rocky/rocky/views/ooi_findings.py
  rocky/rocky/views/ooi_list.py
  rocky/rocky/views/ooi_mute.py
  rocky/rocky/views/ooi_report.py
  rocky/rocky/views/ooi_tree.py
  rocky/rocky/views/ooi_view.py
  rocky/tests/katalogus/test_katalogus_plugin_detail.py
  rocky/tests/objects/test_objects.py
  rocky/tests/test_onboarding_organization_steps.py
Labels: documentation, enhancement, rocky

#817 Updated linter configs
  boefjes/boefjes/__main__.py
  boefjes/boefjes/app.py
  boefjes/boefjes/clients/scheduler_client.py
  boefjes/boefjes/katalogus/dependencies/plugins.py
  boefjes/boefjes/katalogus/local_repository.py
  boefjes/boefjes/plugins/kat_log4shell/main.py
  boefjes/boefjes/plugins/kat_snyk/check_version.py
  boefjes/boefjes/plugins/kat_snyk/normalize.py
  boefjes/boefjes/seed.py
  boefjes/boefjes/sql/db.py
  bytes/tests/integration/__init__.py
  bytes/tests/integration/test_bytes_api.py
  bytes/tests/integration/test_event.py
  bytes/tests/integration/test_hash_service.py
  bytes/tests/integration/test_meta_repository.py
  bytes/tests/integration/test_timestamper.py
  keiko/keiko/cli.py
  keiko/templates/bevindingenrapport/__init__.py
  keiko/templates/dns/__init__.py
  keiko/templates/intel/__init__.py
  keiko/tests/fixtures/__init__.py
  keiko/tests/fixtures/templates/__init__.py
  keiko/tests/fixtures/templates/template1/__init__.py
  keiko/tests/fixtures/templates/template2/__init__.py
  mula/scheduler/repositories/sqlalchemy/datastore.py
  octopoes/bits/spf_discovery/internetnl_spf_parser.py
  octopoes/octopoes/api/api.py
  octopoes/octopoes/tasks/tasks.py
  octopoes/tests/robot/__init__.py
  pyproject.toml
  rocky/tests/account/__init__.py
  rocky/tests/katalogus/__init__.py
  rocky/tests/katalogus/test_katalogus.py
  rocky/tests/katalogus/test_katalogus_plugin_add.py
  rocky/tests/katalogus/test_katalogus_plugin_delete.py
  rocky/tests/katalogus/test_katalogus_plugin_edit.py
  rocky/tools/add_ooi_information.py
  rocky/tools/management/commands/export_migrations.py
  rocky/tools/management/commands/setup_dev_account.py
Labels: python, tech-debt

#820 Implement `pyupgrade` in ruff
  .pre-commit-config.yaml
  boefjes/boefjes/plugins/kat_manual/csv/normalize.py
  boefjes/tests/test_app.py
  bytes/bytes/config.py
  keiko/keiko/logging.py
  mula/scheduler/connectors/connector.py
  mula/scheduler/context/context.py
  octopoes/octopoes/api/api.py
  octopoes/octopoes/tasks/tasks.py
  octopoes/octopoes/xtdb/related_field_generator.py
  pyproject.toml
  rocky/katalogus/views/mixins.py
  rocky/rocky/middleware/otel.py
  rocky/rocky/views/health.py
  rocky/rocky/views/upload_csv.py
  rocky/tools/forms/base.py
  rocky/tools/models.py
Labels: tech-debt

#788 DB schema update scheduler
  mula/Makefile
  mula/scheduler/alembic/env.py
  mula/scheduler/alembic/versions/0005_size_limit_hash.py
  mula/scheduler/models/queue.py
  mula/scheduler/models/tasks.py
Labels: mula

#719 Add stylelint to the CI and `pre-commit`
  .pre-commit-config.yaml
  .stylelintrc.json
  docs/source/_static/openkat.css
Labels: frontend, rocky
