Repository minvws/nl-kat-coordination, pull requests merged in 2024-05, with the labels that each got.

#2672 Add a warning to the CSP validator for 'self' on script-src directives.
  octopoes/bits/check_csp_header/check_csp_header.py
Labels: enhancement, boefjes

#2910 Replace old plugin in Vulnerability Report
  rocky/reports/report_types/vulnerability_report/report.py
Labels: bug, backport

#2919 Update `jinja2` and `tqdm`
  keiko/poetry.lock
  keiko/requirements-dev.txt
  keiko/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/requirements-dev.txt
Labels: dependencies, backport

#2912 Add wappalyzer software to weburl instead of hostname
  boefjes/boefjes/plugins/kat_wappalyzer/normalize.py
Labels: backport

#2972 Updated packages
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  cveapi/poetry.lock
  cveapi/requirements.txt
  keiko/poetry.lock
  keiko/pyproject.toml
  keiko/requirements-dev.txt
  keiko/requirements.txt
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies, 😸 QA feedback

#2953 Fix task api status code response for malformed id in the scheduler
  mula/scheduler/server/server.py
  mula/scheduler/storage/errors.py
  mula/scheduler/storage/filters/errors.py
  mula/scheduler/storage/filters/functions.py
  mula/scheduler/storage/pq_store.py
  mula/scheduler/storage/task_store.py
  mula/tests/integration/test_api.py
  mula/tests/integration/test_task_store.py
Labels: mula

#2813 Adding IPv6 support to documentation for Docker setups
  docs/source/installation_and_deployment/containers.md
Labels: documentation

#2984 Phase out the Repository model from the KATalogus
  boefjes/Makefile
  boefjes/boefjes/config.py
  boefjes/boefjes/katalogus/api/__init__.py
  boefjes/boefjes/katalogus/api/organisations.py
  boefjes/boefjes/katalogus/api/plugins.py
  boefjes/boefjes/katalogus/api/root.py
  boefjes/boefjes/katalogus/api/settings.py
  boefjes/boefjes/katalogus/clients.py
  boefjes/boefjes/katalogus/dependencies/context.py
  boefjes/boefjes/katalogus/dependencies/plugins.py
  boefjes/boefjes/katalogus/dependencies/repositories.py
  boefjes/boefjes/katalogus/local_repository.py
  boefjes/boefjes/katalogus/models.py
  boefjes/boefjes/katalogus/organisations.py
  boefjes/boefjes/katalogus/routers/repositories.py
  boefjes/boefjes/katalogus/static/assets/default_cover.png
  boefjes/boefjes/katalogus/static/assets/kat_ssl_certificates/cover.png
  boefjes/boefjes/katalogus/storage/diskcache.py
  boefjes/boefjes/katalogus/storage/interfaces.py
  boefjes/boefjes/katalogus/storage/memory.py
  boefjes/boefjes/katalogus/tests/integration/test_api.py
  boefjes/boefjes/katalogus/tests/integration/test_json_settings_encryption_migration.py
  boefjes/boefjes/katalogus/tests/integration/test_remove_repository_migration.py
  boefjes/boefjes/katalogus/tests/integration/test_sql_repositories.py
  boefjes/boefjes/katalogus/tests/test_organisations.py
  boefjes/boefjes/katalogus/tests/test_plugin_service.py
  boefjes/boefjes/katalogus/tests/test_plugins.py
  boefjes/boefjes/katalogus/tests/test_repositories.py
  boefjes/boefjes/katalogus/types.py
  boefjes/boefjes/katalogus/v1.py
  boefjes/boefjes/migrations/versions/7c88b9cd96aa_remove_the_repository_model.py
  boefjes/boefjes/seed.py
  boefjes/boefjes/sql/db_models.py
  boefjes/boefjes/sql/organisation_storage.py
  boefjes/boefjes/sql/plugin_enabled_storage.py
  boefjes/boefjes/sql/repository_storage.py
  boefjes/boefjes/sql/setting_storage.py
  boefjes/debian/kat-boefjes.kat-katalogus.service
  boefjes/entrypoint.sh
  boefjes/packaging/deb/data/usr/bin/update-katalogus-db
  boefjes/tests/test_tasks.py
  docker-compose.yml
  docs/source/developer_documentation/boefjes.md
  docs/source/installation_and_deployment/containers.md
  docs/source/release_notes/1.16.rst
  mula/.ci/docker-compose.yml
  rocky/katalogus/client.py
  rocky/tests/conftest.py
  rocky/tests/objects/test_objects_detail.py
  rocky/tests/stubs/katalogus_boefjes.json
  rocky/tests/stubs/katalogus_normalizers.json
  rocky/tests/test_indemnification.py
Labels: boefjes, katalogus

#2957 Rewrite xtdb-cli.py with "click"
  octopoes/octopoes/xtdb/client.py
  octopoes/tools/xtdb-cli.py
  octopoes/tools/xtdb_client.py
Labels: enhancement, tech-debt, xtdb
