Repository minvws/nl-kat-coordination, pull requests merged in 2024-01, with the labels that each got.

#2280 Fixed invalid type usage in `get_rabbit_channel` and `close_rabbit_channel`
  octopoes/octopoes/tasks/tasks.py
Labels: bug, octopoes

#2281 List item behaviour
  rocky/assets/css/components/chapter-numbering.scss
  rocky/assets/css/themes/soft/manon/sidemenu.scss
Labels: frontend

#2317 Updated template file to respect environment prefixes in docs
  docs/settings-doc-templates/markdown.jinja
Labels: bug, documentation

#2326 Fix/upgrade jinja2
  keiko/poetry.lock
  keiko/pyproject.toml
  keiko/requirements-dev.txt
  keiko/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/requirements-dev.txt
Labels: dependencies

#2255 add meta / cache hash for rpki boefje to raw output
  boefjes/boefjes/plugins/kat_rpki/main.py
  boefjes/boefjes/plugins/kat_rpki/normalize.py
  boefjes/boefjes/plugins/kat_rpki/schema.json
Labels: enhancement, boefjes, backport1.14

#2340 Remove icons from compliance issue table
  rocky/reports/report_types/aggregate_organisation_report/system_specific.html
  rocky/reports/report_types/rpki_report/report.html
  rocky/reports/report_types/safe_connections_report/report.html
Labels: UI/UX, design, report

#2220 Feat/normalizer mimetype upload deeplink
  rocky/katalogus/templates/normalizer_detail.html
  rocky/rocky/locale/django.pot
  rocky/rocky/urls.py
  rocky/rocky/views/upload_raw.py
  rocky/tools/forms/upload_raw.py
Labels: rocky

#2348 Update dependencies
  .pre-commit-config.yaml
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  cveapi/poetry.lock
  cveapi/requirements.txt
  keiko/poetry.lock
  keiko/pyproject.toml
  keiko/requirements-dev.txt
  keiko/requirements.txt
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/katalogus/templates/katalogus_settings.html
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies

#2373 Fix WEASYPRINT_BASEURL default value and change ports in docker-compose.yml
  docker-compose.yml
  rocky/rocky/settings.py
Labels: backport1.14

#2374 Prevent double github actions
  .github/workflows/boefjes_container_image.yml
  .github/workflows/boefjes_tests.yml
  .github/workflows/build_docs_on_pr.yml
  .github/workflows/bytes_container_image.yml
  .github/workflows/bytes_tests.yml
  .github/workflows/check_poetry_dependencies.yml
  .github/workflows/debian_package.yml
  .github/workflows/keiko_container_image.yml
  .github/workflows/keiko_itest.yml
  .github/workflows/keiko_test.yml
  .github/workflows/keiko_tex_linters.yml
  .github/workflows/masscan_container_image.yml
  .github/workflows/mula_container_image.yml
  .github/workflows/mula_tests.yml
  .github/workflows/octopoes_container_image.yml
  .github/workflows/octopoes_rtest.yml
  .github/workflows/octopoes_tests.yml
  .github/workflows/pre_commit_checks.yml
  .github/workflows/rocky_container_image.yml
  .github/workflows/rocky_makelang.yml
  .github/workflows/rocky_tests.yml
Labels: tech-debt

#2366 Remove uWSGI
  rocky/packaging/deb/data/etc/kat/rocky.uwsgi.ini
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
  rocky/rocky/settings.py
  rocky/uwsgi.ini
Labels: dependencies, backend

#2396 Update dependencies
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  keiko/poetry.lock
  keiko/pyproject.toml
  keiko/requirements-dev.txt
  keiko/requirements.txt
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies, tech-debt

#2025 Feat/more csp checks
  octopoes/bits/check_csp_header/check_csp_header.py
  octopoes/tests/test_bit_csp_header.py
Labels: enhancement, boefjes
