Repository minvws/nl-kat-coordination, pull requests merged in 2025-04, with the labels that each got.

#4218 Disable `rich` tracebacks
  boefjes/boefjes/__main__.py
  boefjes/boefjes/katalogus/root.py
  boefjes/boefjes/logging.py
  bytes/bytes/api/__init__.py
  mula/scheduler/context/context.py
  octopoes/octopoes/api/api.py
  octopoes/octopoes/tasks/tasks.py
  rocky/rocky/settings.py
Labels: enhancement, backport, backport1.18

#4245 Updated some packages
  boefjes/poetry.lock
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/requirements-dev.txt
  bytes/requirements.txt
  mula/poetry.lock
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies

#4250 Dont allow open redirect in plugin_enable_disable.py
  rocky/katalogus/views/plugin_enable_disable.py
Labels: frontend, security

#4257 Add oci attributes to scheduler
  bytes/bytes/api/router.py
  mula/scheduler/models/boefje.py
  mula/scheduler/models/plugin.py
  mula/tests/factories/boefje.py
  rocky/rocky/scheduler.py
Labels: mula

#4287 Docs - Add links to website and github
  docs/source/index.rst
Labels: documentation

#4217 Limit db and external service calls in scheduler
  mula/scheduler/schedulers/queue/pq.py
  mula/scheduler/schedulers/scheduler.py
  mula/scheduler/schedulers/schedulers/boefje.py
  mula/scheduler/schedulers/schedulers/normalizer.py
  mula/scheduler/schedulers/schedulers/report.py
  mula/tests/integration/test_boefje_scheduler.py
  mula/tests/unit/test_queue.py
Labels: mula

#4305 fix location PR templates
  .github/pull_request_template.md
Labels: documentation

#4299 Fix a regression introduced in #4169 blocking the ability of of `octopoes/tools/xtdb-cli.py` to be called
  docs/source/about-openkat/release-notes/1.18.rst
  octopoes/tools/xtdb-cli.py
Labels: octopoes, xtdb

#4298 Updated dependencies
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  cveapi/poetry.lock
  cveapi/pyproject.toml
  cveapi/requirements.txt
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies, python

#4341 Fixes toc layout on the docs
  .github/pull_request_template.md
  docs/source/about-openkat/faq.rst
  docs/source/about-openkat/index.rst
  docs/source/basics/index.rst
  docs/source/basics/introduction.rst
  docs/source/contributor/guidelines/contributions.rst
  docs/source/contributor/guidelines/development.rst
  docs/source/contributor/guidelines/feature_flow.md
  docs/source/contributor/guidelines/ideas.rst
  docs/source/contributor/guidelines/ideas/KAT - OpenKAT als educatietool.pdf
  docs/source/contributor/guidelines/ideas/OpenKAT - Indemnity statements v0.2.pdf
  docs/source/contributor/guidelines/ideas/Veilige weergave boefjes-data in KAT interface v1.0.pdf
  docs/source/contributor/guidelines/index.rst
  docs/source/contributor/guidelines/management.rst
  docs/source/contributor/guidelines/security.rst
  docs/source/contributor/index.rst
  docs/source/contributor/intro.rst
  docs/source/contributor/templates/bug_report_template.md
  docs/source/contributor/templates/feature_request_template.md
  docs/source/contributor/templates/index.rst
  docs/source/contributor/templates/pull_request_template_author.md
  docs/source/contributor/templates/pull_request_template_review_code.md
  docs/source/contributor/templates/pull_request_template_review_qa.md
  docs/source/contributor/ux-design/figma.rst
  docs/source/contributor/ux-design/index.rst
  docs/source/glossary/glossary.rst
  docs/source/glossary/index.rst
  docs/source/index.rst
  docs/source/quick-start/index.rst
  docs/source/quick-start/quick-start.rst
  docs/source/user-interface/index.rst
  docs/source/user-interface/introduction.rst
  docs/source/user-interface/katalogus.rst
  docs/source/user-interface/reports.rst
Labels: documentation

#4263 Styling changes to meet the design
  rocky/katalogus/templates/about_plugins.html
  rocky/katalogus/templates/boefjes.html
  rocky/katalogus/templates/clone_settings.html
  rocky/katalogus/templates/katalogus.html
  rocky/katalogus/templates/katalogus_settings.html
  rocky/katalogus/templates/normalizers.html
  rocky/katalogus/templates/partials/katalogus_header.html
  rocky/onboarding/templates/dns_report.html
  rocky/reports/templates/partials/main_navigation.html
  rocky/reports/templates/partials/report_severity_totals_table.html
  rocky/reports/templates/report_overview/report_history.html
  rocky/reports/templates/report_overview/report_history_table.html
  rocky/reports/templates/report_overview/report_overview_header.html
  rocky/rocky/locale/django.pot
  rocky/rocky/templates/findings/finding_list.html
  rocky/rocky/templates/oois/ooi_detail.html
  rocky/rocky/templates/oois/ooi_detail_findings_list.html
  rocky/rocky/templates/oois/ooi_detail_findings_overview.html
  rocky/rocky/templates/oois/ooi_list.html
  rocky/rocky/templates/organizations/organization_list.html
  rocky/rocky/templates/organizations/organization_member_list.html
  rocky/rocky/templates/organizations/organization_settings.html
  rocky/rocky/templates/partials/ooi_detail_related_object.html
  rocky/rocky/templates/partials/ooi_head.html
  rocky/rocky/templates/partials/ooi_report_severity_totals.html
  rocky/rocky/templates/partials/ooi_report_severity_totals_table.html
  rocky/rocky/templates/scan_profiles/scan_profile_detail.html
  rocky/rocky/templates/tasks/boefjes.html
  rocky/rocky/templates/tasks/normalizers.html
  rocky/rocky/templates/tasks/ooi_detail_task_list.html
  rocky/rocky/templates/tasks/partials/tasks_overview_header.html
  rocky/rocky/templates/tasks/report_tasks.html
  rocky/tests/katalogus/test_katalogus.py
Labels: frontend, tech-debt

#4264 fix permissions on report_overview.py
  rocky/reports/templates/report_overview/scheduled_reports_table.html
  rocky/reports/views/report_overview.py
  rocky/rocky/locale/django.pot
  rocky/tests/reports/test_report_overview.py
  rocky/tests/reports/test_report_schedules.py
Labels: 😸 Review/QA feedback

#4396 Add organisation queryparam for schedules endpoint
  mula/scheduler/server/handlers/schedules.py
  mula/scheduler/storage/stores/schedule.py
  mula/tests/integration/test_api.py
Labels: mula

#4282 Upgrade jaeger and prometheus, and enable spm
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  docker-compose.yml
  jaeger.yml
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  prometheus.yml
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
  rocky/rocky/otel.py
Labels: scalability

#4394 Add all organization report task page
  rocky/account/models.py
  rocky/reports/templates/tasks/report_tasks_list.html
  rocky/rocky/locale/django.pot
  rocky/rocky/scheduler.py
  rocky/rocky/templates/tasks/partials/tab_navigation.html
  rocky/rocky/templates/tasks/report_tasks.html
  rocky/rocky/templates/tasks/reports.html
  rocky/rocky/urls.py
  rocky/rocky/views/tasks.py
Labels: 😸 Review/QA feedback

#4054 Add min_scan_level to nibbles with phantom result toggle
  octopoes/nibbles/definitions.py
  octopoes/nibbles/runner.py
  octopoes/octopoes/core/service.py
  octopoes/octopoes/models/origin.py
  octopoes/octopoes/repositories/origin_repository.py
  octopoes/tests/integration/test_check_cve_2021_41773_nibble.py
  octopoes/tests/integration/test_default_finding_type_nibble.py
  octopoes/tests/integration/test_dns_alias_nibble.py
  octopoes/tests/integration/test_hsts_nibble.py
  octopoes/tests/integration/test_missing_spf_nibble.py
  octopoes/tests/integration/test_nibbles.py
  octopoes/tests/integration/test_url_discovery_nibble.py
Labels: nibbles
