Repository minvws/nl-kat-coordination, pull requests merged in 2025-05, with the labels that each got.

#4297 Add grafana pyroscope continuous profiling
  docker-compose.yml
  docs/source/installation-and-deployment/local-install.rst
  monitoring/config.alloy
  monitoring/grafana-provisioning/datasources/pyroscope.yml
  monitoring/grafana-provisioning/plugins/explore-profiles.yml
  monitoring/jaeger.yml
  monitoring/prometheus.yml
Labels: scalability, 😸 Review/QA feedback

#4433 Updated packages
  boefjes/poetry.lock
  boefjes/pyproject.toml
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  mula/poetry.lock
  mula/pyproject.toml
  mula/requirements-dev.txt
  mula/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies

#4434 Update GitHub actions
  .github/workflows/boefjes_container_image.yml
  .github/workflows/build-debian-docker-image.yml
  .github/workflows/bytes_container_image.yml
  .github/workflows/codeql.yml
  .github/workflows/containerized_boefjes.yml
  .github/workflows/debian_package.yml
  .github/workflows/masscan_container_image.yml
  .github/workflows/mula_container_image.yml
  .github/workflows/octopoes_container_image.yml
  .github/workflows/rocky_container_image.yml
  .github/workflows/sonar-cloud.yml
Labels: dependencies, github_actions

#4419 Update 1.18.rst, add links to issues / bugs
  docs/source/about-openkat/release-notes/1.18.rst
Labels: documentation

#4289 Docs - add description of origin types
  docs/source/basics/index.rst
  docs/source/basics/origin-types.rst
Labels: documentation, 😸 Review/QA feedback

#4453 Updated packages
  boefjes/poetry.lock
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/requirements-dev.txt
  bytes/requirements.txt
  cveapi/poetry.lock
  cveapi/requirements.txt
  mula/poetry.lock
  mula/requirements-dev.txt
  octopoes/poetry.lock
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
  poetry.lock
  requirements.txt
  rocky/poetry.lock
  rocky/requirements-dev.txt
  rocky/requirements.txt
Labels: dependencies

#4441 Updated Django and other packages
  rocky/account/views/login.py
  rocky/poetry.lock
  rocky/pyproject.toml
  rocky/requirements-dev.txt
  rocky/requirements.txt
  rocky/rocky/settings.py
Labels: dependencies, rocky

#4472 Updated packages
  boefjes/poetry.lock
  boefjes/requirements-dev.txt
  boefjes/requirements.txt
  bytes/poetry.lock
  bytes/pyproject.toml
  bytes/requirements-dev.txt
  bytes/requirements.txt
  octopoes/poetry.lock
  octopoes/pyproject.toml
  octopoes/requirements-dev.txt
  octopoes/requirements.txt
Labels: dependencies

#4408 Add exponential backoff for external service requests in scheduler
  mula/scheduler/clients/http/service.py
Labels: mula

#4350 Fix delete recipe modal
  rocky/reports/templates/report_overview/scheduled_reports_table.html
  rocky/reports/templates/report_schedules/delete_recipe_modal.html
  rocky/reports/views/report_overview.py
  rocky/rocky/locale/django.pot
  rocky/rocky/scheduler.py
  rocky/rocky/views/ooi_edit.py
  rocky/rocky/views/scheduler.py
  rocky/tests/reports/test_report_schedules.py
Labels: bug

#4423 use the active filter dict as an input for the count.
  rocky/rocky/views/finding_list.py
  rocky/rocky/views/ooi_view.py
Labels: bug, rocky

#4410 Update scheduler to shutdown when external services are not reachable
  mula/scheduler/schedulers/schedulers/boefje.py
  mula/scheduler/schedulers/schedulers/normalizer.py
  mula/scheduler/storage/utils.py
  mula/tests/integration/test_boefje_scheduler.py
  mula/tests/integration/test_normalizer_scheduler.py
Labels: mula

#4477 Check member permissions instead of user permissions for recalculating bits
  rocky/rocky/views/organization_settings.py
Labels: rocky, tech-debt

#4481 Stop hardcoding internet
  octopoes/bits/oois_in_headers/oois_in_headers.py
  octopoes/tests/test_bits.py
Labels: octopoes, bits

#4487 Update organization_crisis_room_header.html
  rocky/crisis_room/templates/organization_crisis_room_header.html
Labels: backport1.19
